const boxMass = [
  {
    boxValue: 430,
    boxColor: 'черный',
    id: 1,
    url: 'https://s38.wheelsage.org/format/picture/picture-gallery-full/c/cadillac/fleetwood_brougham/cadillac_fleetwood_brougham_19.jpg',
    car: 'Cadillac Fleetwood',
  },
  {
    boxValue: 420,
    boxColor: 'серый',
    id: 2,
    url: 'https://s36.wheelsage.org/format/picture/picture-gallery-full/c/cadillac/escalade/cadillac_escalade_34_02ac01540c500936.jpg',
    car: 'Cadillac Escalade',
  },
  {
    boxValue: 550,
    boxColor: 'черный',
    id: 3,
    url: 'https://s38.wheelsage.org/format/picture/picture-gallery-full/c/cadillac/escalade/cadillac_escalade_794.jpg',
    car: 'Cadillac Escalade',
  },
  {
    boxValue: 460,
    boxColor: 'черный',
    id: 4,
    url: 'https://s36.wheelsage.org/format/picture/picture-gallery-full/c/cadillac/fleetwood_sixty_special/cadillac_fleetwood_sixty_special_14_011601120c010906.jpg',
    car: 'Cadillac Fleetwood',
  },
  {
    boxValue: 550,
    boxColor: 'белый',
    id: 5,
    url: 'https://s38.wheelsage.org/format/picture/picture-gallery-full/t/toyota/tundra_trd_pro_crewmax/toyota_tundra_trd_pro_crewmax_0380031407ab05c1.jpg',
    car: 'Toyota Tundra',
  },
  {
    boxValue: 400,
    boxColor: 'серый',
    id: 6,
    url: 'https://s36.wheelsage.org/format/picture/picture-gallery-full/t/toyota/tundra_limited_crewmax_trd_off-road/toyota_tundra_limited_crewmax_trd_off-road_8_00e800000a9507d0.jpg',
    car: 'Toyota Tundra',
  },
  {
    boxValue: 420,
    boxColor: 'серый',
    id: 7,
    url: 'https://s38.wheelsage.org/format/picture/picture-gallery-full/toyota/land_cruiser/autowp.ru_toyota_land_cruiser_100_5.jpg',
    car: 'Toyota Land Cruiser',
  },
  {
    boxValue: 430,
    boxColor: 'белый',
    id: 8,
    url: 'https://s38.wheelsage.org/format/picture/picture-gallery-full/toyota/land_cruiser/autowp.ru_toyota_land_cruiser_100_vx_jp-spec_17.jpg',
    car: 'Toyota Land Cruiser',
  },
  {
    boxValue: 460,
    boxColor: 'серый',
    id: 9,
    url: 'https://s38.wheelsage.org/format/picture/picture-gallery-full/ford/crown_victoria/autowp.ru_ford_crown_victoria_56.jpg',
    car: 'Ford Crown Victoria',
  },
  {
    boxValue: 1000,
    boxColor: 'белый',
    id: 10,
    url: 'https://s38.wheelsage.org/format/picture/picture-gallery-full/f/ford/crown_victoria_ngv_police_interceptor/ford_crown_victoria_ngv_police_interceptor.jpg',
    car: 'Ford Crown Victoria',
  },
  {
    boxValue: 1000,
    boxColor: 'серый',
    id: 11,
    url: 'https://s36.wheelsage.org/format/picture/picture-gallery-full/a/amg/mercedes-benz/s-klasse/mercedes-benz_s-klasse_amg_1.jpg',
    car: 'Mercedes-Benz W140',
  },
  {
    boxValue: 400,
    boxColor: 'черный',
    id: 12,
    url: 'https://s38.wheelsage.org/format/picture/picture-gallery-full/m/mercedes-benz/s_600_l/mercedes-benz_s_600_l_8.jpg',
    car: 'Mercedes-Benz W140',
  },
]

export default boxMass
